### PR TITLE
Modify claimblock accrual idle detection and handling

### LINKED ISSUE #1060: Players cannot gain or accrue claim blocks if they are legitimately swimming in water or underwater
### What happened:
When a player swims or is underwater they don't gain any claim blocks. The plugin says they weren't active for the round. This is especially a problem if a player is building underwater bases and structures with a Conduit.

### What was expected:
Players should gain Claim Blocks if they're legitimately fully submerged in water swimming or moving underwater

### Steps to reproduce:
1. Enable Debug logs via Config
2. Ensure you can gain claim blocks through normal play
3. Ensure you have enough room to gain Claim Blocks
4. Swim around in an Ocean Biome and explore underwater for 20 minutes or longer
5. Check logs and check how many blocks are earned (no blocks are earned)

### Server and GriefPrevention version:
___This can be found by running `/version` and `/version GriefPrevention` on your server.___
Paste of `/version`:  This server is running Paper version git-Paper-209 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
Paste of `/version GriefPrevention`: GriefPrevention version 16.14.0

### Stack trace/error or server log

```
03:50 Looking for expired claims.  Checking data for 7d84598a-7928-4bd1-83cf-67a15fdd378a
03:51 ACChapV2 wasn't active enough to accrue claim blocks this round.
03:51 Looking for expired claims.  Checking data for f6be97bb-a09c-413b-8d00-ae4cc3e3f658
03:51 Delivering 3 blocks to AnimalTheGamer
03:51 Delivering 3 blocks to Sonku
03:52 Looking for expired claims.  Checking data for 01a882da-a689-4e97-b271-f04211822456
03:53 Looking for expired claims.  Checking data for 1c30cb9e-8cc2-4387-8a16-d072bdc48e6b
03:54 Looking for expired claims.  Checking data for 23d3b018-554f-43d8-8e3d-dd472eed05f6
03:55 Looking for expired claims.  Checking data for 15946a9e-66e3-476b-931e-dd009cfc6955
03:56 Looking for expired claims.  Checking data for face8aae-c26d-4b06-8ac0-f7980e09032d
03:57 Looking for expired claims.  Checking data for 3915be44-fb74-4940-be60-a0d68fd17686
03:58 Looking for expired claims.  Checking data for 6be2dfff-a310-4ef9-89ae-170293a12115
03:59 Looking for expired claims.  Checking data for 7995c5ac-9ff1-4c08-94e5-5f9ddcc879f7
03:59 Player is online. Ignoring.
04:00 Looking for expired claims.  Checking data for e88274eb-3f51-4d60-bc1a-d95481218303
04:00 Player is online. Ignoring.
04:01 ACChapV2 wasn't active enough to accrue claim blocks this round.
04:01 Looking for expired claims.  Checking data for 23ecd50f-68f0-4b92-9782-6e222522c98c
04:01 Delivering 3 blocks to AnimalTheGamer
04:01 Sonku wasn't active enough to accrue claim blocks this round.
04:02 The following UUIDs own a claim and will be checked for inactivity in the following order:
04:02 15946a9e-66e3-476b-931e-dd009cfc6955
04:02 01a882da-a689-4e97-b271-f04211822456
04:02 23ecd50f-68f0-4b92-9782-6e222522c98c
04:02 7d84598a-7928-4bd1-83cf-67a15fdd378a
04:02 3915be44-fb74-4940-be60-a0d68fd17686
04:02 face8aae-c26d-4b06-8ac0-f7980e09032d
04:02 7995c5ac-9ff1-4c08-94e5-5f9ddcc879f7
04:02 f6be97bb-a09c-413b-8d00-ae4cc3e3f658
04:02 1c30cb9e-8cc2-4387-8a16-d072bdc48e6b
04:02 e88274eb-3f51-4d60-bc1a-d95481218303
04:02 23d3b018-554f-43d8-8e3d-dd472eed05f6
04:02 6be2dfff-a310-4ef9-89ae-170293a12115
04:03 Looking for expired claims.  Checking data for 15946a9e-66e3-476b-931e-dd009cfc6955
04:04 Looking for expired claims.  Checking data for 01a882da-a689-4e97-b271-f04211822456
04:05 Looking for expired claims.  Checking data for 23ecd50f-68f0-4b92-9782-6e222522c98c
04:06 Looking for expired claims.  Checking data for 7d84598a-7928-4bd1-83cf-67a15fdd378a
04:07 Looking for expired claims.  Checking data for 3915be44-fb74-4940-be60-a0d68fd17686
04:08 Looking for expired claims.  Checking data for face8aae-c26d-4b06-8ac0-f7980e09032d
04:09 Looking for expired claims.  Checking data for 7995c5ac-9ff1-4c08-94e5-5f9ddcc879f7
04:09 Player is online. Ignoring.
04:10 Looking for expired claims.  Checking data for f6be97bb-a09c-413b-8d00-ae4cc3e3f658
04:11 Delivering 3 blocks to ACChapV2
04:11 Looking for expired claims.  Checking data for 1c30cb9e-8cc2-4387-8a16-d072bdc48e6b
04:11 Sonku wasn't active enough to accrue claim blocks this round.
04:11 Delivering 3 blocks to AnimalTheGamer
04:12 Looking for expired claims.  Checking data for e88274eb-3f51-4d60-bc1a-d95481218303
04:12 Player is online. Ignoring.
04:13 Looking for expired claims.  Checking data for 23d3b018-554f-43d8-8e3d-dd472eed05f6
04:14 Looking for expired claims.  Checking data for 6be2dfff-a310-4ef9-89ae-170293a12115
04:15 The following UUIDs own a claim and will be checked for inactivity in the following order:
04:15 01a882da-a689-4e97-b271-f04211822456
04:15 f6be97bb-a09c-413b-8d00-ae4cc3e3f658
04:15 7995c5ac-9ff1-4c08-94e5-5f9ddcc879f7
04:15 7d84598a-7928-4bd1-83cf-67a15fdd378a
04:15 23ecd50f-68f0-4b92-9782-6e222522c98c
04:15 6be2dfff-a310-4ef9-89ae-170293a12115
04:15 23d3b018-554f-43d8-8e3d-dd472eed05f6
04:15 3915be44-fb74-4940-be60-a0d68fd17686
04:15 1c30cb9e-8cc2-4387-8a16-d072bdc48e6b
04:15 15946a9e-66e3-476b-931e-dd009cfc6955
04:15 face8aae-c26d-4b06-8ac0-f7980e09032d
04:15 e88274eb-3f51-4d60-bc1a-d95481218303

```
Or, paste the server.log at gist.github.com and paste the link here: 

### GriefPrevention config.yml

```yml

Paste the config.yml right here inside these backticks. Please do not use a paste service for this.

`# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    NetherArena: -1
    RedSpawn: -1
    world_gold: -1
    world_1: -1
    world_2: -1
  Claims:
    Mode:
      NetherArena: Survival
      world_2: Survival
      world_nether: Disabled
      RedSpawn: Survival
      world: Disabled
      world_gold: Survival
      world_1: Survival
      world_the_end: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 20
    Max Accrued Claim Blocks:
      Default: 5000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 30
      AllClaims:
        DaysInactive: 90
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 0
    LoginLogoutNotificationsPerMinute: 120
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 1
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
      NetherArena: true
      RedSpawn: true
      world_gold: true
      world_1: true
      world_2: false
    ProtectFreshSpawns: false
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  CheckPistonMovement: false
  LimitPistonsToLandClaims: false
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: false
  SmartBan: false
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS_BLOCK
    - GRASS
    - FERN
    - DEAD_BUSH
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - GLASS_PANE
    - OAK_PLANKS
    - SPRUCE_PLANKS
    - BIRCH_PLANKS
    - JUNGLE_PLANKS
    - ACACIA_PLANKS
    - DARK_OAK_PLANKS
    - WHITE_WOOL
    - ORANGE_WOOL
    - MAGENTA_WOOL
    - LIGHT_BLUE_WOOL
    - YELLOW_WOOL
    - LIME_WOOL
    - PINK_WOOL
    - GRAY_WOOL
    - LIGHT_GRAY_WOOL
    - CYAN_WOOL
    - PURPLE_WOOL
    - BLUE_WOOL
    - BROWN_WOOL
    - GREEN_WOOL
    - RED_WOOL
    - BLACK_WOOL
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 1
    Included Entry Types:
      Social Activity: false
      Suspicious Activity: false
      Administrative Activity: false
      Debug: true
      Muted Chat Messages: false``

### Plugin list (if applicable):



### Debugging steps attempted
<!--These will be checkboxes you can click after creating the issue)-->
- [ ] I attempted running only GriefPrevention on the server
  - [ ] Issue still occurs even if GriefPrevention is the only plugin running
- [ ] I attempted testing for the issue on a new server
  - [ ] Issue still occurs even after testing on a new server

### LINKED ISSUE #2366: No claimblock increase when sitting
### Observed Behavior

When player is sitting, for example on a horse or using GSit plugin the passive claimblock increase stops.

### Expected Behavior

Claimblocks should increase regardless if player is sitting, standing, laying down or swimming

### Reproduction steps

1. Sit on a horse or /sit using GSit plugin
2. Observe claim blocks not increasing

### Stack trace or error log

_No response_

### Server version

```shell
[Fri 10:35:50 INFO ] Current Purpur Version: 1.21-2276-72ccfbd (MC: 1.21)
```

### GriefPrevention version

```shell
[Fri 10:36:31 INFO ] GriefPrevention version 16.18.4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: 319
    world_nether: 319
    world_the_end: 319
    targ: -1
    test: -1
    flat: -1
  Claims:
    Mode:
      world_nether: Survival
      targ: Disabled
      world_the_end: Disabled
      world: Survival
      test: Survival
      flat: Disabled
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 0
    Claim Blocks Accrued Per Hour:
      Default: 25
    Max Accrued Claim Blocks:
      Default: 999999
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 15
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 800
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 300
      UnusedClaimDays: 300
      AllClaims:
        DaysInactive: 300
        ExceptWhenOwnerHasTotalClaimBlocks: 100000
        ExceptWhenOwnerHasBonusClaimBlocks: 20000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: false
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
      targ: true
      test: true
      flat: true
    ProtectFreshSpawns: false
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: true
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 25.0
    ClaimBlocksSellValue: 20.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - PURPLE_WOOL
    - LIGHT_GRAY_WOOL
    - GRAVEL
    - BROWN_WOOL
    - DEAD_BUSH
    - BLUE_WOOL
    - JUNGLE_PLANKS
    - GLASS
    - SAND
    - WHITE_WOOL
    - YELLOW_WOOL
    - GLASS_PANE
    - DIRT
    - ORANGE_WOOL
    - BLACK_WOOL
    - GRASS_BLOCK
    - OAK_PLANKS
    - SHORT_GRASS
    - FERN
    - ACACIA_PLANKS
    - MAGENTA_WOOL
    - PINK_WOOL
    - COBBLESTONE
    - RED_WOOL
    - GRAY_WOOL
    - SNOW
    - BIRCH_PLANKS
    - LIME_WOOL
    - CYAN_WOOL
    - SPRUCE_PLANKS
    - GREEN_WOOL
    - DARK_OAK_PLANKS
    - LIGHT_BLUE_WOOL
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: true
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell
GPExtension, GPFlags, GriefPrevention, GSit
```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

### PR DESCRIPTION
**Pull request by RoboMWM**
- always call AccrueClaimBlocksEvent, even when player is detected as idle
- call AccrueClaimBlocksEvent as canceled if player is idle (default GP behavior)
- removes idle accrual and related config options
- only use player direction for idle detection

I'm bad at titles. While some stuff is removed, the event firing behavior has changed to allow more control to addons (API feature addition).

### CODE REVIEW

**Comment by RoboMWM** [comment]
This change would also make the idea mentioned in https://github.com/GriefPrevention/GriefPrevention/issues/2366#issuecomment-2336465946 possible

File: src/main/java/me/ryanhamshire/GriefPrevention/DeliverClaimBlocksTask.java [hunk 1]
```diff
@@ -67,45 +65,27 @@ public void run()
...
         boolean isIdle = false;
-        try
-        {
-            isIdle = player.isInsideVehicle() || player.getLocation().getBlock().isLiquid() ||
-                    !(playerData.lastAfkCheckLocation == null || playerData.lastAfkCheckLocation.distanceSquared(player.getLocation()) > idleThresholdSquared);
-        }
-        catch (IllegalArgumentException ignore) //can't measure distance when to/from are different worlds
-        {
-        }
+        isIdle = !(playerData.lastAfkCheckLocation == null || playerData.lastAfkCheckLocation.getYaw() != player.getLocation().getYaw());
```
Comment (Jikoo) [inline src/main/java/me/ryanhamshire/GriefPrevention/DeliverClaimBlocksTask.java]: We may want to just compare `Location#getDirection` here as that will include pitch too. Highly unlikely that a player would change one but not the other, but it's theoretically possible.

**Review by Jikoo — APPROVED** [review]
LGTM 👍

File: src/main/java/me/ryanhamshire/GriefPrevention/DeliverClaimBlocksTask.java (hunk 1 above)
Comment (RoboMWM) [reply src/main/java/me/ryanhamshire/GriefPrevention/DeliverClaimBlocksTask.java]: ah, I forgot to look through all the location methods when doing this to see if there was such a direction method. Not sure what I did here, probably just started typing "get" and scrolled a little too fast perhaps.

Yea, I think I just glazed right over it lol. This is why I appreciate reviews (pairing would be better but this ain't a job) even for myself xd.

File: src/main/java/me/ryanhamshire/GriefPrevention/DeliverClaimBlocksTask.java [hunk 2]
```diff
@@ -67,45 +65,27 @@ public void run()
...
         boolean isIdle = false;
-        try
-        {
-            isIdle = player.isInsideVehicle() || player.getLocation().getBlock().isLiquid() ||
-                    !(playerData.lastAfkCheckLocation == null || playerData.lastAfkCheckLocation.distanceSquared(player.getLocation()) > idleThresholdSquared);
-        }
-        catch (IllegalArgumentException ignore) //can't measure distance when to/from are different worlds
-        {
-        }
+        isIdle = !(playerData.lastAfkCheckLocation == null || playerData.lastAfkCheckLocation.getDirection() != player.getLocation().getDirection());
```
Comment (Jikoo) [inline src/main/java/me/ryanhamshire/GriefPrevention/DeliverClaimBlocksTask.java]: Will this compare work? I would think we'd need a .equals comparison here.

**Review by Jikoo — CHANGES_REQUESTED** [review]

File: src/main/java/me/ryanhamshire/GriefPrevention/DeliverClaimBlocksTask.java (hunk 2 above)
Comment (RoboMWM) [reply src/main/java/me/ryanhamshire/GriefPrevention/DeliverClaimBlocksTask.java]: yea thanks, I was getting an error with trying to use .equals with getYaw, forgot to switch back.
