### PR TITLE
Removal of onTNTExitPortal

### LINKED ISSUE #2119: Server crash when TnT goes through end portal
### Observed Behavior

When primed TNT goes through end portal server crashed.

### Expected Behavior

It shouldn't crash.

### Reproduction steps

1. Create end portal
2. Send a primed TNT through it.
3. Server crashed.

### Stack trace or error log

```shell
Description: Exception in server tick loop

java.lang.IllegalStateException: Ticking retired scheduler
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:147)
	at net.minecraft.server.MinecraftServer.lambda$tickChildren$14(MinecraftServer.java:1491)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:655)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1484)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

### Server version

```shell
This server is running Paper version git-Paper-100 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: f402f89)
```

### GriefPrevention version

```shell
GriefPrevention version 16.18.1-7-g64b348a
```

### Configuration

```yaml
Default config
```

### Plugin list

```shell
[10:28:14 INFO]: Server Plugins (1):
[10:28:14 INFO]: Bukkit Plugins:
[10:28:14 INFO]:  - GriefPrevention
```

### Running without GriefPrevention

- [X] I attempted running the server without GriefPrevention installed.
- [X] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [X] I attempted running only GriefPrevention on the server.
- [X] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [X] I attempted testing for the issue on a new server.
- [X] The issue still occurs on a new server.

### Using unmodified client

- [X] I attempted testing for the issue with the vanilla client.
- [X] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [X] I searched for similar issues before submitting this bug report.

### PR DESCRIPTION
**Pull request by TreemanKing**
~~Removes the entity preemptively rather than reactively.~~

Edit: Removes the event entirely.

Fixes #2119

### CODE REVIEW

File: src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java [hunk 1]
```diff
@@ -335,11 +335,11 @@ public void onFallingBlockEnterPortal(EntityPortalEnterEvent event)
     //Don't let people drop in TNT through end portals
     //Necessarily this shouldn't be an issue anyways since the platform is obsidian...
     @EventHandler(ignoreCancelled = true)
-    void onTNTExitPortal(EntityPortalExitEvent event)
+    void onTNTExitPortal(EntityPortalEnterEvent event)
     {
         if (event.getEntityType() != EntityType.PRIMED_TNT)
             return;
-        if (event.getTo().getWorld().getEnvironment() != Environment.THE_END)
+        if (event.getLocation().getBlock().getType() == Material.END_PORTAL)
```
Comment (RoboMWM) [inline src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: Would this handle cases of end portal blocks that don't actually end up teleporting an entity/are plugin-handled/end portals in non-default worlds?

Comment (TreemanKing) [reply src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: Yes, will deal with all of the above. 

Using the EntityEnterPortalEvent, you can only determine the location of entry and what block it is. 

It shouldn't interfere with any portal plugins, however would probably be best to be configurable for future references if the server admins would like it to be close to the vanilla state.

Comment (Jikoo) [reply src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: I think Robo's more asking "will this result in TNT that is not teleporting being removed" and I believe the answer is yes, though I'm not sure that it matters much. We could swap to the EntityTeleportEvent instead and see if it's from an end world to a non-end world with the correct cause.

Comment (TreemanKing) [reply src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: Yes, it would although as you said I don't believe there are many problems that could arise as a result of this change. In most cases, if the End hasn't been generated, the TNT will just drop into the lava at the end portal structure.

In terms of clashes with other possible plugins which use portals, they would probably there own instances to remove other entities from teleporting.

I've attempted the EntityTeleportEvent before this and it would still crash the server.

Comment (Jikoo) [reply src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: It crashes even when cancelled? That seems shocking, honestly. Either way, yeah, I don't see this implementation as being problematic.

Comment (TreemanKing) [reply src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: Yeah, I tried that method first before attempting this one. Obviously the destination would be a lot better to use but it would also crash the server.

**Comment by RoboMWM** [comment]
My modification of Portalstick (well, an addon) uses the gateway portal blocks. I know it isn't the same portal block being used here (though I did initially use this), but if I were using that block in another plugin, I wouldn't want to have teleporting entities just get deleted on me.

**Comment by Jikoo** [comment]
> I wouldn't want to have teleporting entities just get deleted on me.

That does make sense, but I think the key part here is that the entity is TNT - teleporting TNT smells of some weird niche grief attempt.

Could add a config option for it, i.e. "BlockTeleportTNT" and just deny TP rather than remove?

**Comment by TreemanKing** [comment]
If you just cancel the event, wouldn't it just be the same as removing the entity? 

I also agree that if it's TNT, it would only cause harm and would probably be disabled for most plugins regardless due to its functionality only being for excavating, grief or farms.

I'll have a go at the configuration as well.

**Comment by TreemanKing** [comment]
I've chucked it in. Let me know if it's alright. Also let me know if you want me to revert back to the other method (even though it isn't efficient in the slightest to do it like it was)

**Comment by RoboMWM** [comment]
The more I think about this the more I see that it's better to just remove. This does appear to be a weird niche, where it could be attempts to cause issues with overworld or the_end spawn. Given the comments, it's probably about the latter. Either way, I don't really see much of a use case for either situation - if the end spawn is desired to be protected, then a claim will solve that immediately. The only thing then I could think of is explosion damage.

The config is a bit ambiguous, and would require looking at documentation to determine what it is. I'm more in favor of just removing this for now. However, since it was reported - I do wonder if it's still a concern for grief... who else has encountered this bug? I want more input on this.

Also it seems that Paper has pushed a fix to this. https://github.com/PaperMC/Paper/commit/408a9050baf29341b877a7bebff0939442d818d0

**Comment by TreemanKing** [comment]
> The more I think about this the more I see that it's better to just remove. This does appear to be a weird niche, where it could be attempts to cause issues with overworld or the_end spawn. Given the comments, it's probably about the latter. Either way, I don't really see much of a use case for either situation - if the end spawn is desired to be protected, then a claim will solve that immediately. The only thing then I could think of is explosion damage.
> 
> The config is a bit ambiguous, and would require looking at documentation to determine what it is. I'm more in favor of just removing this for now. However, since it was reported - I do wonder if it's still a concern for grief... who else has encountered this bug? I want more input on this.
> 
> Also it seems that Paper has pushed a fix to this. https://github.com/PaperMC/Paper/commit/408a9050baf29341b877a7bebff0939442d818d0

I encountered the crash in testing but I honestly think it is completely redundant. It can honestly just be admin claimed and you'll be protected on the platform spawn. I'll edit the PR to remove it entirely if so.

**Comment by RoboMWM** [comment]
ya, I don't have much feedback on this (idk who else I should ask) but I see no need to handle it, so can just remove it ye.

**Review by RoboMWM — APPROVED** [review]
