### PR TITLE
Protect claims from player-caused knockback (wind charges, spears)

### LINKED ISSUE #2536: Wind Charges still apply knockback to players in claims
### Observed Behavior

Wind Charges still apply knockback to players standing in claims. While the previous patch did add protection to block update changes caused by Wind Charges this bug report is regarding the knockback they cause to players.

This can be abused by shooting wind charges into claims or used in claims to push other players (who might be afk) or also possibly mob entities (didnt check this one) outside of their protected claim. 

### Expected Behavior

I am not sure the best protection implemtation for this but some solutions could be:

- Treat Wind Charge knockback the same as PVP and dissallow it using the pvp logic
- Treat Wnid Charge knockback the same as claimexplosions and have that toggle enable/disable them within a claim
- Allow wind charge knockback from trusted players while disallowing it if the source is an untrusted player

### Reproduction steps

1. Create Claim
2. Use Windcharge
3. Get knocked back

### Stack trace or error log

```shell

```

### Server version

```shell
Uspigot 1.21.10
```

### GriefPrevention version

```shell
Using build from this commit: 2a04aaf511d8404a0e920d4fc3a9c324e1280f05
(https://github.com/GriefPrevention/GriefPrevention/commit/2a04aaf511d8404a0e920d4fc3a9c324e1280f05)
```

### Configuration

```yaml
Unrelated
```

### Plugin list

```shell

```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [x] I searched for similar issues before submitting this bug report.

### LINKED ISSUE #2547: Spears can be used to hit or push a mob inside a claim
### Observed Behavior

Untrusted players are able to push mobs with a spear from outside another player's claim. This allows them to force mobs out of the protected area, then kill the mobs once they are outside the claim. This effectively bypasses claim protections and can be used for griefing.

### Expected Behavior

Untrusted players should not be able to interact with or move mobs inside a claim in any way that results in them leaving the protected area.

### Reproduction steps

Steps to reproduce:
1. Create a claim with animal mobs or dogs or cats inside
2. Have another player who is not trusted in the claim stand outside the claim boundary.
3. Use a spear to hit or push a mob inside the claim.
4. The mob is pushed out of the claim boundary.
5. The untrusted player kills the mob once it leaves the claim.

### Stack trace or error log

```shell

```

### Server version

```shell
This server is running UniverseSpigot version 1.21.11-ver/1.21.11@44de5dc (2026-01-08T13:46:21Z) (Implementing API version 1.21.11-R0.1-SNAPSHOT)
UniverseSpigot-1.21.11-44de5dc (MC: 1.21.11)
```

### GriefPrevention version

```shell
GriefPrevention version 18.0.0-3-g5b7d6c4
```

### Configuration

```yaml
# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/

GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
    Space: -1
    MazeGame: -1
    Egypt: -1
    pvp: -1
    VoidEvent: -1
    netherhub: -1
    spawn: -1
    medieval_arena: -1
    minigames: -1
    resource_world: -1
    CATCRAFTMARKET: -1
  Claims:
    Mode:
      spawn: Survival
      world: Survival
      pvp: Survival
      CATCRAFTMARKET: Disabled
      resource_world: Survival
      world_nether: Survival
      minigames: Disabled
      Egypt: Survival
      VoidEvent: Disabled
      netherhub: Disabled
      Space: Survival
      world_the_end: Survival
      MazeGame: Disabled
      medieval_arena: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 1000
    Claim Blocks Accrued Per Hour:
      Default: 200
    Max Accrued Claim Blocks:
      Default: 80000
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 64
    MinimumWidth: 5
    MinimumArea: 100
    MinimumY: -2147483648
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 7
      AllClaims:
        DaysInactive: 90
        ExceptWhenOwnerHasTotalClaimBlocks: 3400
        ExceptWhenOwnerHasBonusClaimBlocks: 3400
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 300
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: false
    LoginCooldownSeconds: 20
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: false
      world_nether: false
      world_the_end: false
      Space: true
      MazeGame: true
      Egypt: true
      pvp: true
      VoidEvent: true
      netherhub: true
      spawn: true
      medieval_arena: true
      minigames: true
      resource_world: true
      CATCRAFTMARKET: false
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 10
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: false
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE_SIMPLE
  PistonExplosionSound: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  VisualizationAntiCheatCompatMode: false
  SmartBan: true
  Mute New Players Using Banned Words: false
  MaxPlayersPerIpAddress: 15
  SilenceBans: true
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  MobProjectilesChangeBlocks: false
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 360
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
  ConfigVersion: 1
```

### Plugin list

```shell

```

### Running without GriefPrevention

- [ ] I attempted running the server without GriefPrevention installed.
- [ ] The problem does _not_ occur when GriefPrevention is removed from the server.

### Running with only GriefPrevention

- [ ] I attempted running only GriefPrevention on the server.
- [ ] The issue still occurs when GriefPrevention is the only plugin running.

### Running on a fresh, clean server installation

- [ ] I attempted testing for the issue on a new server.
- [ ] The issue still occurs on a new server.

### Using unmodified client

- [ ] I attempted testing for the issue with the vanilla client.
- [ ] The issue still occurs when using the vanilla client.

### We appreciate you taking the time to fill out a bug report!

- [x] I searched for similar issues before submitting this bug report.

### PR DESCRIPTION
**Pull request by FreeMonoid**
Adds protection against players using knockback mechanics to push entities out of claims where they lack trust. This covers wind charges, spears, and any other player-caused knockback that might be added in the future.

PvP interactions:
- Self-boosting always allowed (e.g., wind charge mobility)
- Admins bypass all checks if ignoring claims
- Container trust allows pushing other players in the claim
- In PvE worlds, knockback between players is blocked
- In PvP worlds, knockback is allowed unless:
  - Either player is a fresh spawn, or
  - Either player is in a PvP safe zone

PvE interactions:
- Armor stands and hanging entities require build trust
- Animals require container trust (if creature protection is enabled)
- Monsters are never protected

Closes #2536
Closes #2547

### CODE REVIEW

**Comment by FreeMonoid** [comment]
@RoboMWM and maybe @Jikoo / @QarthO — would appreciate your input for the direction of this PR
 
The changes technically work in the current state, but on Paper we get deprecation notice:
```
[21:27:47 WARN]: [GriefPrevention] "GriefPrevention v16.18.5-7-g9c5c211" has registered a listener for org.bukkit.event.entity.EntityKnockbackByEntityEvent on method "public void me.ryanhamshire.GriefPrevention.EntityDamageHandler.onEntityKnockbackByEntity(org.bukkit.event.entity.EntityKnockbackByEntityEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [].
```
since https://jd.papermc.io/paper/1.21.10/org/bukkit/event/entity/EntityKnockbackByEntityEvent.html is deprecated and slated for removal

I don't know what our stance on Paper-specific additions currently are: are we OK with them at all? Should I just use reflection to decide which event we want to listen to depending on runtime platform or do we have another approach somewhere?

**Comment by RoboMWM** [comment]
> I don't know what our stance on Paper-specific additions currently are

Ok but should not be required.

> Should I just use reflection to decide which event we want to listen to depending on runtime platform or do we have another approach somewhere?

Idk if reflection is required? But I'm thinking this may be the direction we want to go, initialize one or another class depending on platform.

**Comment by Jikoo** [comment]
Didn't realize this was legacy at first and wrote a whole long thing about how we really need to modularize the project for future support of both Paper and Spigot. Whoopsies.

The biggest problem imo is that we need a Paper dependency for the Paper events, so we need a Paper module. The main Spigot side can then just conditionally choose to use our Paper version or the regular version when registering events.

Reflective platform determination sounds good. I believe usually one targets config classes, but if we have specific listeners we want to enable, we could target the event class each is supposed to listen to for extra security.

**Comment by FreeMonoid** [comment]
@RoboMWM @Jikoo alright, finally got the time to take a stab at this 😅  Would love your reviews when you have time, guys!

File: src/main/java/me/ryanhamshire/GriefPrevention/EntityDamageHandler.java [hunk 1]
```diff
@@ -75,13 +75,17 @@ public class EntityDamageHandler implements Listener
...
     private final @NotNull GriefPrevention instance;
-    private final @NotNull NamespacedKey luredByPlayer;
+    private static NamespacedKey luredByPlayer;
 
     EntityDamageHandler(@NotNull DataStore dataStore, @NotNull GriefPrevention plugin)
     {
         this.dataStore = dataStore;
         instance = plugin;
-        luredByPlayer = new NamespacedKey(plugin, "lured_by_player");
+        // Static field initialization - safe because only one instance is created at startup
```
Comment (Jikoo) [inline src/main/java/me/ryanhamshire/GriefPrevention/EntityDamageHandler.java]: How would we feel about using NamespacedKey#ofString or whichever the method is and just making this statically initialized instead? I don't love potentially making things initialization-order-dependent even if it isn't really much of a risk.

**Review by Jikoo — APPROVED** [review]
LGTM overall, clean way to add this without having to add a new module.

File: src/main/java/me/ryanhamshire/GriefPrevention/EntityDamageHandler.java (hunk 1 above)
Comment (FreeMonoid) [reply src/main/java/me/ryanhamshire/GriefPrevention/EntityDamageHandler.java]: Yes, good point, that's a good idea! Converted it in ed57669

**Comment by RoboMWM** [comment]
I'm still thinking about this - I know this is for legacy but especially for master and moving forward I'm still thinking about how spigot vs. paper registration should happen; if it'd be more desirable to offload specifically that to a separate class and have the actual handling elsewhere.

tho I guess this probably enters what jikoo wants to do with modules perhaps.

just haven't had the contiguous time to dedicate to how the approach should look.

**Comment by FreeMonoid** [comment]
Yeah, makes sense, that's why I haven't even seriously thought about porting this to master: these changes are just enough to get by in the meantime 😅

**Comment by FreeMonoid** [comment]
@Jikoo after chatting with @RoboMWM on Discord, I've added a slim abstraction (or at least what I hope you'll consider slim!) for impl-specific listeners. Should give us a bit more structure for adding new ones in the future.

Open to bikeshedding or any other thoughts!

**Review by Jikoo — APPROVED** [review]
This looks clean, it seems like a very neat and expandable way to handle the issue without major structural changes.

**Comment by FreeMonoid** [comment]
@RoboMWM @Jikoo in the light of more people reporting spears also causing an issue with entity knockback, I've generalized this PR to check all the `EntityKnockbackByEntityEvent`s

Tested it with spears and wind charges and they work as expected now

There's a particular cause I'm not sure if we want to treat in a special way: 
- [SHIELD_BLOCK](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityKnockbackEvent.KnockbackCause.html#SHIELD_BLOCK) Knockback caused by the target blocking with a shield.

I _think_ our general handling (trusted players can cause knockback, untrusted can't) should be fine in this case as well, but wanted to bring it up just in case since it gave me a pause when considering if we should keep _some_ filtering by cause in the handler or not.

**Comment by Jikoo** [comment]
Does this also handle maces now then? Shield-based knockback I think we can ignore, because the knockback target would have to be the aggressor, right? Kinda consenting to being thrown around if you're punching someone with a shield up.

**Comment by FreeMonoid** [comment]
@Jikoo we actually prevent knockback from mace smash attack already by canceling the `EntityDamageByEntityEvent` in the latest release already, so this PR doesn't change anything about that, if I understood you correctly 😅 

The knockback from wind charges, spears, etc. isn't dependent on damage, so they also fire `EntityKnockbackByEntityEvent`, which is why our usual protections didn't catch it and we need special handling

**Comment by FreeMonoid** [comment]
Oh, and for shield knockback: I was thinking of the case when untrusted player defends from owner/trustee — their blocking won't cause knockback to the owner/trustee, which is kind of an advantage to the latter, but it's also their claim so plenty of other advantages 🤷

**Comment by Jikoo** [comment]
> @Jikoo we actually prevent knockback from mace smash attack already by canceling the `EntityDamageByEntityEvent` in the latest release already, so this PR doesn't change anything about that, if I understood you correctly 😅

Specifically talking about #2473 for the Burst enchantment, which I believe acts like a wind charge. Sorry, should have clarified.

**Comment by FreeMonoid** [comment]
@Jikoo didn't realize mace AoE smash attack actually triggered yet another type of event, `EntityPushedByEntityAttackEvent` (Paper-only, Spigot doesn't have an equivalent) — added handling for it to the Paper handler 😅 

There's a caveat though: mace with Wind Burst bypasses cancelation and causes knockback/push anyway (https://github.com/PaperMC/Paper/issues/13079)

(Even without Wind Burst mace does AoE push, Wind Burst also adds self-knockback to the player similar to wind charge)

**Review by RoboMWM — APPROVED** [review]

**Comment by RoboMWM** [comment]
> Animals require container trust (if creature protection is enabled)

Wondering if this should be changed to preventTheft as per https://github.com/GriefPrevention/GriefPrevention/blob/5b7d6c484fd611f024ba068bd031883197dcea9a/src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L1197-L1198

> Container trust allows pushing other players in the claim

Thoughts on whether this should be accesstrust instead?

Current behavior pre windcharge addition was players could be pushed by collisions (client-side calculation as far as I'm aware) and was always permitted. I'm assuming windcharges are more effective in that they pusha player much farther and easier, and spammable from range... but thinking about each of the trust tiers, I think accesstrust makes the most sense.

Offtopic, but I really think we should rename ClaimPermission#Inventory to ClaimPermission#Container, I initially confused Inventory with accesstrust somehow.

**Comment by FreeMonoid** [comment]
1. Yeah, I guess we use `protectCreatures` to mean whether creatures can be harmed, and in this case it is more about theft — changed it to use `preventTheft` instead 👍 
2. Good point too: I guess I was trying to be more conservative and ensure only the people you really trust can push you around, but your example about regular player-player collision is very on point
3. Yep, `Inventory` has been minutely bugging me too, but it's an external API change so 😬  I will make a separate PR into `master` with the changes to see how much it will affect internally

**Review by RoboMWM — APPROVED** [review]
