### PR TITLE
Handle ignited entities melting powdered snow

### LINKED ISSUE #1561: Powder snow can be griefed without trust, by walking into it while being on fire
### What happened:
Walking into powder snow inside a claim, while on fire, removes the powder snow block with no trust in the claim.

### What was expected:
The powder snow block should stay in place if no trust.

### Steps to reproduce:
1. Player one creates a claim with noone trusted
2. Player one place powder snow inside the claim
3. Player two shoots themself with fire arrow and then walk into the powder snow while being on fire. The powder snow block will then disappear.

### Server and GriefPrevention version:
Paste of `/version`: This server is running Paper version git-Paper-239 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: ca708a0)
Paste of `/version GriefPrevention`: GriefPrevention version 85b76cc

### Stack trace/error or server log
I have not included server log, as I don't want to expose the entire chat log here. If it's still needed, I'll see what I can do.

### GriefPrevention config.yml

```yml
GriefPrevention:
  SeaLevelOverrides:
    world: -1
    world_nether: -1
    world_the_end: -1
  Claims:
    Mode:
      world: Survival
      world_the_end: Survival
      world_nether: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: true
    LockTrapDoors: true
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    RaidTriggersRequireBuildTrust: true
    ProtectHorses: true
    ProtectDonkeys: true
    ProtectLlamas: true
    InitialBlocks: 225
    Claim Blocks Accrued Per Hour:
      Default: 150
    Max Accrued Claim Blocks:
      Default: 300000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    AutomaticNewPlayerClaimsRadiusMinimum: 0
    ExtendIntoGroundDistance: 20
    MinimumWidth: 1
    MinimumArea: 10
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLDEN_SHOVEL
    Expiration:
      ChestClaimDays: 9999999
      UnusedClaimDays: 9999999
      AllClaims:
        DaysInactive: 9999999
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
    RavagersBreakBlocks: true
    FireSpreadsInClaims: false
    FireDamagesInClaims: false
    LecternReadingRequiresAccessTrust: true
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local;/minecraft:me;/tpa;/suicide
    WhisperSlashCommands: ''
    WarningMessage: Please reduce your noise level.  Spammers will be muted.
    BanOffenders: false
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 60
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      world: true
      world_nether: true
      world_the_end: true
    ProtectFreshSpawns: true
    PunishLogout: false
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: true
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: false
      AdministrativeClaims: false
      AdministrativeSubdivisions: false
    AllowLavaDumpingNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    AllowFlintAndSteelNearOtherPlayers:
      PvPWorlds: false
      NonPvPWorlds: false
    ProtectPetsOutsideLandClaims: true
  Economy:
    ClaimBlocksMaxBonus: 0
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: true
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: false
  BlockSurfaceOtherExplosions: false
  LimitSkyTrees: false
  LimitTreeGrowth: false
  PistonMovement: EVERYWHERE
  PistonExplosionSound: true
  FireSpreads: true
  FireDestroys: true
  AdminsGetWhispers: false
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 5
  SilenceBans: true
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS     <-- can't understand this entry, see BukkitDev documentation
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS     <-- can't understand this entry, see BukkitDev documentation
    - WOOD     <-- can't understand this entry, see BukkitDev documentation
    - WOOL     <-- can't understand this entry, see BukkitDev documentation
    - SNOW
    DoorsOpenDelayInSeconds: 300
    CooldownEndInMinutes: 60
  EndermenMoveBlocks: true
  SilverfishBreakBlocks: true
  CreaturesTrampleCrops: true
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: true
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Advanced:
    fixNegativeClaimblockAmounts: true
    ClaimExpirationCheckRate: 60
    OfflinePlayer_cache_days: 90
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: false
      Administrative Activity: true
      Debug: false
      Muted Chat Messages: true
```

### Plugin list (if applicable):
AntiXRay, AutoMessage, BuycraftX, Chunky, CommandHook, EntityWatch, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, F3NPerm, GriefPrevention, HolographicDisplays, InteractiveBooks, InventoryRollback, LogBlock, LuckPerms, Matrix, OpenInv, PlugMan, ProtocolLib, Reports, Vault, VoteRoulette, Votifier, WorldEdit, WorldGuard

### Debugging steps attempted

- [ ] (If applicable) I attempted running the server without GriefPrevention installed
  - [ ] (If applicable) The problem does _not_ occur if GriefPrevention is removed from the server.
- [x] I attempted running only GriefPrevention on the server
  - [x] Issue still occurs even if GriefPrevention is the only plugin running
- [x] I attempted testing for the issue on a new server
  - [x] Issue still occurs even after testing on a new server
- [x] I attempted testing for the issue with the vanilla client (no mods)
  - [x] Issue still occurs even after testing with the vanilla Minecraft client

### PR DESCRIPTION
**Pull request by Jikoo**
Closes #1561

### CODE REVIEW

File: src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java [hunk 1]
```diff
@@ -283,6 +290,38 @@ private void handleProjectileChangeBlock(EntityChangeBlockEvent event, Projectil
...
+        // Note: this does not handle flaming arrows; they are handled earlier by #handleProjectileChangeBlock
+        Player player = null;
+        if (event.getEntity() instanceof Player localPlayer)
+        {
+            player = localPlayer;
+        }
+        else if (event.getEntity() instanceof Mob mob)
+        {
+            // Handle players leading packs of zombies.
+            if (mob.getTarget() instanceof Player localPlayer) player = localPlayer;
```
Comment (RoboMWM) [inline src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: Hmm, is convention sameline oneliners, or newline oneliners? Thought it was the latter, but I haven't been working with this codebase much lately (and I hopefully plan to change that within the coming weeks).

**Review by RoboMWM — CHANGES_REQUESTED** [review]

File: src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java (hunk 1 above)
Comment (Jikoo) [reply src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: A mix, usually one line for shorter ones. If you want to move to always having a newline, that's fine by me. Either way it feels a little alien, I always use braces these days, even for single lines, but with the newline before opening braces that takes up a lot of space.

Comment (RoboMWM) [reply src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: I always do newline for oneliners, since at least for my brain, I always recognize one line for performing either an action or evaluating a condition, not both.

Comment (RoboMWM) [reply src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: However if this is convention elsewhere, then that's fine, and I can change later.

Comment (Jikoo) [reply src/main/java/me/ryanhamshire/GriefPrevention/EntityEventHandler.java]: Gotcha. Was trying to fix it, but managed to break my rebase and am having A Time. I guess I could just slap a newline in in the editor.
/e: My best guess is that I somehow locked the rebase folder when Git was trying to delete it, so I was "rebasing" nothing and resetting the head couldn't fix it.

**Review by RoboMWM — APPROVED** [review]
